"""Utility modules for the AI Adoption Dashboard."""

from .error_handler import (
    ErrorCategory,
    ErrorHandler,
    ErrorRecovery,
    ErrorSeverity,
    handle_errors,
    safe_data_load,
    safe_visualization,
    setup_logging,
)
from .types import (
    AccessibilityConfig,
    CacheConfig,
    ChartConfig,
    ChartData,
    ConfigDict,
    DashboardData,
    DataFrameDict,
    DataSourceInfo,
    ErrorInfo,
    FilterConfig,
    MetricData,
    MetricDict,
    OptionalDataFrame,
    OptionalDict,
    OptionalList,
    PerformanceMetrics,
    PersonaConfig,
    ThemeConfig,
    ViewConfig,
    ViewData,
)

__all__ = [
    # Error handling
    "ErrorHandler",
    "ErrorSeverity",
    "ErrorCategory",
    "ErrorRecovery",
    "handle_errors",
    "setup_logging",
    "safe_data_load",
    "safe_visualization",
    # Type definitions
    "DashboardData",
    "MetricData",
    "ChartConfig",
    "ViewConfig",
    "PersonaConfig",
    "CacheConfig",
    "PerformanceMetrics",
    "ErrorInfo",
    "DataSourceInfo",
    "FilterConfig",
    "ThemeConfig",
    "AccessibilityConfig",
    "DataFrameDict",
    "MetricDict",
    "ConfigDict",
    "ChartData",
    "ViewData",
    "OptionalDataFrame",
    "OptionalDict",
    "OptionalList",
]
