"""Utility modules for the AI Adoption Dashboard."""

from .error_handler import (
    ErrorCategory,
    ErrorHandler,
    ErrorRecovery,
    ErrorSeverity,
    handle_errors,
    safe_data_load,
    safe_visualization,
    setup_logging,
)
from .types import (
    AccessibilityConfig,
    CacheConfig,
    ChartConfig,
    ChartData,
    ConfigDict,
    DashboardData,
    DataFrameDict,
    DataSourceInfo,
    ErrorInfo,
    FilterConfig,
    MetricData,
    MetricDict,
    OptionalDataFrame,
    OptionalDict,
    OptionalList,
    PerformanceMetrics,
    PersonaConfig,
    ThemeConfig,
    ViewConfig,
    ViewData,
)
from .cache_manager import (
    CacheManager,
    CalculationCache,
    cached,
    cache_financial_calculation,
    cache_monte_carlo,
    cache_sensitivity_analysis,
    calculation_cache,
)
from .audit_logger import (
    AuditEventType,
    AuditSeverity,
    AuditEntry,
    AuditLogger,
    audit_logger,
    audit_calculation,
)

__all__ = [
    # Error handling
    "ErrorHandler",
    "ErrorSeverity",
    "ErrorCategory",
    "ErrorRecovery",
    "handle_errors",
    "setup_logging",
    "safe_data_load",
    "safe_visualization",
    # Type definitions
    "DashboardData",
    "MetricData",
    "ChartConfig",
    "ViewConfig",
    "PersonaConfig",
    "CacheConfig",
    "PerformanceMetrics",
    "ErrorInfo",
    "DataSourceInfo",
    "FilterConfig",
    "ThemeConfig",
    "AccessibilityConfig",
    "DataFrameDict",
    "MetricDict",
    "ConfigDict",
    "ChartData",
    "ViewData",
    "OptionalDataFrame",
    "OptionalDict",
    "OptionalList",
    # Cache management
    "CacheManager",
    "CalculationCache",
    "cached",
    "cache_financial_calculation",
    "cache_monte_carlo",
    "cache_sensitivity_analysis",
    "calculation_cache",
    # Audit logging
    "AuditEventType",
    "AuditSeverity",
    "AuditEntry",
    "AuditLogger",
    "audit_logger",
    "audit_calculation",
]
